data:
  train_ratio: 0.9
  data_dir: dataset

model:
  dropout: 0.2

training:
  epochs: 10
  batch_size: 32
  optimizer: adam
  lr: 0.001
  warmup_ratio: 0.1
  validation_split: 0.2
  checkpoint_dir: checkpoints/
  model_name: best_model
  device: mps
  evaluation_metric: accuracy
  best_metric_lower_is_better: false
