data:
  train_ratio: 0.85
  test_val_ratio: 0.35
  data_dir: dataset

model:
  dropout: 0.25

training:
  epochs: 40
  batch_size: 16
  optimizer: adam
  base_lr: 0.005
  min_lr: 0.001
  warmup_ratio: 0.3
  checkpoint_dir: checkpoints/
  model_name: best_model
  device: mps
  evaluation_metric: accuracy
  best_metric_lower_is_better: false

plot: [accuracy, loss]
