data:
  train_ratio: 0.8
  test_val_ratio: 0.4
  data_dir: dataset

model:
  dropout: 0.2

training:
  epochs: 20
  batch_size: 32
  optimizer: adam
  lr: 0.005
  warmup_ratio: 0.2
  checkpoint_dir: checkpoints/
  model_name: best_model
  device: mps
  evaluation_metric: accuracy
  best_metric_lower_is_better: false
